name: Go CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  ci:
    name: Build, Lint, and Test
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.25.3'
          cache: true

      - name: Download dependencies
        run: go mod tidy

      - name: Check Formatting (gofmt)
        run: test -z "$(gofmt -s -l .)"

      - name: Go Vet
        run: go vet ./...

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v2.12.2

      - name: Run Tests
        run: go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...
