name: Dev Release

on:
  push:
    branches: [dev]
  workflow_dispatch:

jobs:
  ci:
    name: Build, Lint, and Test
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.25.3"
          cache: true

      - name: Download dependencies
        run: go mod tidy

      - name: Check Formatting (gofmt)
        run: test -z "$(gofmt -s -l .)"

      - name: Go Vet
        run: go vet ./...

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.12.2

      - name: Run Tests
        run: go test -v  ./...

  build-image:
    runs-on: ubuntu-24.04
    needs: ci

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Login docker
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Build Tag
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build and Push Image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/go-server:dev-${{ steps.vars.outputs.sha_short }}
            ghcr.io/${{ github.repository_owner }}/go-server:dev-latest
