name: Production Deploy

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

concurrency:
  group: prod-deploy
  cancel-in-progress: false

jobs:
  deploy-prod:
    name: Deploy Image to Production Server
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Get CI-Matching Hash
        id: vars
        run: |
          echo "COMMIT_HASH=$(git rev-parse --short=7 HEAD)" >> $GITHUB_OUTPUT

      - name: SSH into Production Server
        uses: appleboy/ssh-action@v1.2.5
        with:
          host: ${{ secrets.PROD_SERVER_IP }}
          username: admin
          key: ${{ secrets.PROD_SSH_KEY }}
          script: |
            echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

            IMAGE_TAG="dev-${{ steps.vars.outputs.COMMIT_HASH }}"

            docker pull ghcr.io/${{ github.repository_owner }}/go-server:$IMAGE_TAG || exit 1

            docker stop go-server-prod || true
            docker rm go-server-prod || true

            docker run --name go-server-prod -d \
              --restart unless-stopped \
              -p 8080:8080 \
              ghcr.io/${{ github.repository_owner }}/go-server:$IMAGE_TAG

            docker image prune -f
