name: Production Deploy

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

concurrency:
  group: prod-deploy
  cancel-in-progress: false

jobs:
  get-commit:
    name: Get commit
    runs-on: ubuntu-24.04
    outputs:
      commit_hash: ${{ steps.vars.outputs.COMMIT_HASH }}
    steps:
      - uses: actions/checkout@v4
      - id: vars
        run: echo "COMMIT_HASH=$(git rev-parse --short=7 HEAD)" >> $GITHUB_OUTPUT

  deploy-prod:
    name: Deploy to production server
    needs: get-commit
    uses: ./.github/workflows/deploy-ssh.yaml
    with:
      username: admin
      container_name: go-server-prod
      image_tag: dev-${{ needs.get-commit.outputs.commit_hash }}
      host: ${{ vars.PROD_SERVER_IP }}
    secrets:
      ssh_key: ${{ secrets.PROD_SSH_KEY }}
      ghcr_pat: ${{ secrets.GHCR_PAT }}
